<?php if (count($flash) > 0): ?>
    <ul>
        <?php foreach ($flash as $messages): ?>
            <?php foreach ($messages as $message): ?>
                <li><?= $message ?></li>
            <?php endforeach ?>
        <?php endforeach ?>
    </ul>
<?php endif ?>

<a href="/posts/new">Новый пост</a>

<!-- BEGIN (write your solution here) -->
<?php if (count($posts) > 0): ?>
    <ul>
        <?php foreach ($posts as $post): ?>
            <li>
                <form action="/posts/<?= $post['id'] ?>" method="post">
                    <a href="/posts/<?= $post['id'] ?>/edit"><?= $post['name']?></a>
                    <input type="hidden" name="_METHOD" value="DELETE">
                    <input type="submit" value="Remove">
                </form>
            </li>
        <?php endforeach ?>
    </ul>
<?php endif ?>
<!-- END -->
