<!--<form action="/cart-items" method="post">
    <input type="hidden" name="item[id]" value="1">
    <input type="hidden" name="item[name]" value="One">
    One
    <input type="submit" value="Add">
</form>

<form action="/cart-items" method="post">
    <input type="hidden" name="item[id]" value="2">
    <input type="hidden" name="item[name]" value="Second">
    Second
    <input type="submit" value="Add">
</form>

<form action="/cart-items" method="post">
    <input type="hidden" name="_METHOD" value="delete">
    <input type="submit" value="Clean">
</form>

<?php if (count($cart) == 0): ?>
    <div>Cart is empty</div>
<?php else: ?>
    <?php foreach ($cart as $item): ?>
        <div>
            <?= htmlspecialchars($item['name']) ?>: <?= htmlspecialchars($item['count']) ?>
        </div>
    <?php endforeach ?>
<?php endif ?>-->

<?php if (count($flash) > 0): ?>
    <ul>
        <?php foreach ($flash as $messages): ?>
            <?php foreach ($messages as $message): ?>
                <li><?= $message ?></li>
            <?php endforeach ?>
        <?php endforeach ?>
    </ul>
<?php endif ?>

<?php if ($currentUser): ?>
    <div><?= $currentUser['name'] ?></div>
    <form action="/session" method="post">
        <input type="hidden" name="_METHOD" value="DELETE">
        <input type="submit" value="Sign Out">
    </form>
<?php else: ?>
    <form action="/session" method="post">
        <input type="text" required name="user[name] "value="">
        <input type="password" required name="user[password] "value="">
        <input type="submit" value="Sign In">
    </form>
<?php endif; ?>

