<style>
    table {text-align: left;}
</style>
<a href="/users">Пользователи</a>
<p>
<table>
    <caption>Пользователь</caption>
    <tr>
        <th>Поле</th>
        <th>Значение</th>
    </tr>
    <tr><td>ID</td><td><?= $id ?></td></tr>
    <tr><td>First name</td><td><?= $firstName ?></td></tr>
    <tr><td>Last name</td><td><?= $lastName ?></td></tr>
    <tr><td>Email</td><td><?= $email ?></td></tr>
</table>
</p>

